- alias: Who Cook
  trigger:
    platform: state
    entity_id: input_select.who_cooks
  action:
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "Today Cook {{ trigger.to_state.state }}"