#-------------------------------------------
#  Package to extract version information for my docker containers
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Package Details:
#   Usage:
#     Markdown card showing version updates
#   Dependancies:
#     philhawthorne/ha-dockermon:edge docker image
#   Sensors:
#     Github version sensors for repos that tag their latest release
#     Docker version sensors for docker containers whitelisted in ha-dockermon
#-------------------------------------------

#-------------------------------------------
# Package Notes:
#   Need to add MQTT (Eclipse) somehow 
#   Need to add Caddy somehow 
#   Need to add HassDB (MariaDB) somehow 
#   Need to add Unifi Docker somehow 
#   Need to add Unifi DB (MongoDB) somehow 
#-------------------------------------------

sensor:

#-------------------------------------------
# RESTful - https://www.home-assistant.io/integrations/rest/
#-------------------------------------------

  - platform: rest
    name: github_nzbget_version
    resource: 'https://api.github.com/repos/linuxserver/docker-nzbget/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_radarr_version
    resource: 'https://api.github.com/repos/linuxserver/docker-radarr/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_sonarr_version
    resource: 'https://api.github.com/repos/linuxserver/docker-sonarr/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_tautulli_version
    resource: 'https://api.github.com/repos/linuxserver/docker-tautulli/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_unifi_poller_version
    resource: 'https://api.github.com/repos/unifi-poller/unifi-poller/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_adminer_version
    resource: 'https://api.github.com/repos/vrana/adminer/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_adguardhome_version
    resource: 'https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_alertmanager_version
    resource: 'https://api.github.com/repos/prometheus/alertmanager/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_cadvisor_version
    resource: 'https://api.github.com/repos/google/cadvisor/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_dozzle_version
    resource: 'https://api.github.com/repos/amir20/dozzle/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_grafana_version
    resource: 'https://api.github.com/repos/grafana/grafana/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_node_exporter_version
    resource: 'https://api.github.com/repos/prometheus/node_exporter/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_nodered_version
    resource: 'https://api.github.com/repos/node-red/node-red/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600
  - platform: rest
    name: github_prometheus_version
    resource: 'https://api.github.com/repos/prometheus/prometheus/releases/latest'
    headers:
      accept: application/vnd.github.v3+json
      content-type: application/json
      user-agent: home-assistant/rest-sensor
    value_template: >-
      {{ value_json.tag_name }}
    scan_interval: 3600

#-------------------------------------------
# Template Sensor - https://www.home-assistant.io/integrations/template/
#-------------------------------------------

  - platform: template
    sensors:
      docker_nzbget_version:
        value_template: >-
          {{ state_attr('switch.nzbget','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_radarr_version:
        value_template: >-
          {{ state_attr('switch.radarr','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_sonarr_version:
        value_template: >-
          {{ state_attr('switch.sonarr','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_tautulli_version:
        value_template: >-
          {{ state_attr('switch.tautulli','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_unifi_poller_version:
        value_template: >-
          {{ state_attr('switch.unifi_poller','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_adminer_version:
        value_template: >-
          {{ state_attr('switch.adminer','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_adguardhome_version:
        value_template: >-
          {{ state_attr('switch.adguardhome','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_alertmanager_version:
        value_template: >-
          {{ state_attr('switch.alertmanager','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_cadvisor_version:
        value_template: >-
          {{ state_attr('switch.cadvisor','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_dozzle_version:
        value_template: >-
          {{ state_attr('switch.dozzle','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_grafana_version:
        value_template: >-
          {{ state_attr('switch.grafana','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_node_exporter_version:
        value_template: >-
          {{ state_attr('switch.nodeexporter','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_nodered_version:
        value_template: >-
          {{ state_attr('switch.nodered','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}
      docker_prometheus_version:
        value_template: >-
          {{ state_attr('switch.prometheus','image')|regex_replace(find='^.*?\:', replace='', ignorecase=False) }}