homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 140.72
  customize: !include_dir_merge_named customize

# ###################### #
# # Homeassistant Basics #
# ###################### #

# https://home-assistant.io/components/emulated_hue/
emulated_hue:
  host_ip: !secret hassio
  listen_port: 8300
  expose_by_default: false
  exposed_domains:
    - light

sun:
config:
hassio:
updater:
discovery:
conversation:
logbook:
frontend:
  themes:
    green:
      primary-color: "#6CA518"
tts:
  - platform: google

# ############################################### #
# # IFTTT Configuration                         # #
# # https://home-assistant.io/components/ifttt/ # # 
# ############################################### #

ifttt:
  key: !secret ifttt_key

# ################################################ #
# # Logger Configuration                         # #
# # https://home-assistant.io/components/logger/ # # 
# ################################################ #

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: info
    homeassistant.components.automation: debug
    homeassistant.components.light: info
    homeassistant.components.sensor: info
    homeassistant.components.scene: info
    homeassistant.components.switch: info
    homeassistant.components.mqtt: debug

feedreader:
  urls:
    - https://home-assistant.io/atom.xml
    - https://github.com/blog.atom
    - https://hasspodcast.io/feed/podcast
    
# ############################################### #
# # Enables                                     # #
# # detailed information in corresponding files # # 
# ############################################### #

binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
history: !include history.yaml
http: !include http.yaml
group: !include group.yaml
light: !include light.yaml
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
remote: !include remote.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
switch: !include switch.yaml
weblink: !include weblink.yaml
zone: !include zones.yaml

# ############################################### #
# # Enables Directories                         # #
# # detailed information in corresponding files # # 
# ############################################### #

automation: !include_dir_merge_list automation
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_slider: !include_dir_merge_named input_slider
scene: !include_dir_merge_list scene