---

# ############################################### #
# # Light Configuration                         # #
# # https://home-assistant.io/components/light/ # # 
# ############################################### #

# https://home-assistant.io/components/light.hue/
- platform: hue
  host: !secret huehub_ip
  allow_unreachable: True
  allow_hue_groups: False

# https://home-assistant.io/components/light.hyperion/
- platform: hyperion
  host: !secret pilivingroom_ip
  port: 19444
  name: TV Lights