## Created by Jeroen Klompen
## More-page add-on: Coronavirus
## Version: 1.0.1

- type: horizontal-stack
  cards:
    - type: custom:mini-graph-card
      style: |
        ha-card {
          background-color: var(--dwains-theme-primary);
        }
      entities:
        - sensor.united_kingdom_coronavirus_confirmed
      name: United Kingdom Current
      line_color: 'var(--dwains-theme-accent)'
      hours_to_show: 168
      hour24: true
      points_per_hour: 0.25
      smoothing: true
      show:
        points: false
        graph: line
      #   extrema: false

    - type: custom:mini-graph-card
      style: |
        ha-card {
          background-color: var(--dwains-theme-primary);
        }
      entities:
        - sensor.worldwide_coronavirus_confirmed
      name: Worldwide Current
      line_color: 'var(--dwains-theme-accent)'
      hours_to_show: 168
      hour24: true
      points_per_hour: 0.25
      smoothing: true
      show:
        points: false
        graph: line
      #   extrema: false

- type: glance
  show_icon: true
  show_name: true
  show_state: true
  title: United Kingdom
  style: |
    ha-card {
      padding: 8px;
      background-color: var(--dwains-theme-primary);
    }
  entities:
    - entity: sensor.united_kingdom_coronavirus_confirmed
      icon: 'mdi:emoticon-neutral-outline'
      name: Confirmed
    - entity: sensor.united_kingdom_coronavirus_current
      icon: 'mdi:emoticon-frown-outline'
      name: Current
    - entity: sensor.united_kingdom_coronavirus_recovered
      icon: 'mdi:emoticon-happy-outline'
      name: Recovered
    - entity: sensor.united_kingdom_coronavirus_deaths
      icon: 'mdi:emoticon-dead-outline'
      name: Deaths

- type: glance
  show_icon: true
  show_name: true
  show_state: true
  title: Worldwide
  style: |
    ha-card {
      padding: 8px;
      background-color: var(--dwains-theme-primary);
    }
  entities:
    - entity: sensor.worldwide_coronavirus_confirmed
      icon: 'mdi:emoticon-neutral-outline'
      name: Confirmed
    - entity: sensor.worldwide_coronavirus_current
      icon: 'mdi:emoticon-frown-outline'
      name: Current
    - entity: sensor.worldwide_coronavirus_recovered
      icon: 'mdi:emoticon-happy-outline'
      name: Recovered
    - entity: sensor.worldwide_coronavirus_deaths
      icon: 'mdi:emoticon-dead-outline'
      name: Deaths