# Resources Page

# https://github.com/custom-cards/nintendo-wishlist-card
- type: module
  url: /hacsfiles/nintendo-wishlist-card/nintendo-wishlist-card.js

# GUI Sandbox Card https://github.com/thomasloven/lovelace-gui-sandbox
- url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js
  type: module

# Weather Card https://github.com/bramkragten/weather-card
- url: /hacsfiles/weather-card/weather-card.js
  type: module

# Swipe Card https://github.com/bramkragten/swipe-card
- url: /hacsfiles/swipe-card/swipe-card.js
  type: module

# Mini Graph Card https://github.com/kalkih/mini-graph-card
- url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  type: module

# Custom Header https://github.com/maykar/custom-header
- url: /hacsfiles/custom-header/custom-header.js
  type: module

# Card-Mod https://github.com/thomasloven/lovelace-card-mod
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module

# Layout Card https://github.com/thomasloven/lovelace-layout-card
- url: /hacsfiles/lovelace-layout-card/layout-card.js
  type: module

# Light Entity Card https://github.com/ljmerza/light-entity-card
- url: /hacsfiles/light-entity-card/light-entity-card.js
  type: js

# Vertical-Stack-in-Card Card https://github.com/ofekashery/vertical-stack-in-card
- url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  type: js

# Card Tools https://github.com/thomasloven/lovelace-card-tools
- url: /hacsfiles/lovelace-card-tools/card-tools.js
  type: module

# Mini Media Player Card https://github.com/kalkih/mini-media-player
- url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  type: module

# Upcoming Media Card https://github.com/custom-cards/upcoming-media-card
- url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
  type: js

# Button Card https://github.com/custom-cards/button-card
- url: /hacsfiles/button-card/button-card.js
  type: module

# Bar Card https://github.com/custom-cards/bar-card
- url: /hacsfiles/bar-card/bar-card.js
  type: module

# Circle Sensor Card https://github.com/custom-cards/circle-sensor-card
- url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
  type: module    

# Auto Entities https://github.com/thomasloven/lovelace-auto-entities
- url: /hacsfiles/lovelace-auto-entities/auto-entities.js
  type: module

# Banner Card https://github.com/nervetattoo/banner-card
- url: /hacsfiles/banner-card/banner-card.js
  type: module

# Secondaryinfo Entity Row https://github.com/custom-cards/secondaryinfo-entity-row
- url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
  type: module 

# Unused Card https://github.com/custom-cards/unused-card
- url: /hacsfiles/unused-card/unused-card.js
  type: module 

# Thermostat Card https://github.com/fineemb/lovelace-thermostat-card
- url: /hacsfiles/lovelace-thermostat-card/main.js
  type: module

# https://github.com/gadgetchnnel/lovelace-card-templater
- url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
  type: module

# https://github.com/azuwis/zigbee2mqtt-networkmap
- url: /hacsfiles/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js
  type: module

# https://github.com/thomasloven/lovelace-slider-entity-row
- url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
  type: module

# https://github.com/maxwroc/battery-state-card
- url: /hacsfiles/battery-state-card/battery-state-card.js
  type: module

# https://github.com/gadgetchnnel/lovelace-home-feed-card
- url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
  type: module

# https://github.com/thomasloven/lovelace-more-info-card
- type: module 
  url: /hacsfiles/lovelace-more-info-card/more-info-card.js

# https://github.com/thomasloven/lovelace-state-switch
- type: module
  url: /hacsfiles/lovelace-state-switch/state-switch.js

# https://github.com/bramkragten/swipe-card
- type: module
  url: /hacsfiles/swipe-card/swipe-card.js

# https://github.com/gadgetchnnel/lovelace-card-preloader
- type: module
  url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js

# https://github.com/gadgetchnnel/lovelace-card-preloader
- type: module
  url: /hacsfiles/lovelace-card-preloader/lovelace-card-preloader.js

# https://github.com/DBuit/light-popup-card
- type: module
  url: /hacsfiles/light-popup-card/light-popup-card.js

# https://github.com/thomasloven/lovelace-hui-element
- type: module
  url: /hacsfiles/lovelace-hui-element/hui-element.js

# https://github.com/thomasloven/lovelace-hui-element
- type: module
  url: /hacsfiles/popup-backdrop-filter/popup-backdrop-filter.js

# https://github.com/custom-cards/stack-in-card
- type: module
  url: /hacsfiles/stack-in-card/stack-in-card.js

# https://github.com/matt8707/hass-config
- type: module
  url: /local/fonts/custom_icons.js

# https://github.com/matt8707/hass-config
- type: css
  url: /local/fonts/font.css