- alias: Mamma at Home - Notification
  trigger:
     platform: zone
     event: enter
     zone: zone.home
     entity_id: device_tracker.mamma_mamma
  action:
   service: notify.homenicoassistant_bot
   data:
     message: "Mamma is at Home at {{ states('sensor.date__time') }}"

- alias: Mamma Outside Home - Notification
  trigger:
     platform: zone
     event: leave
     zone: zone.home
     entity_id: device_tracker.mamma_mamma
  action:
   service: notify.homenicoassistant_bot
   data:
     message: "Mamma is going out at {{ states('sensor.date__time') }}"