# lovelace_gen
---

##############
# Server Tab #
##############
- title: Server
  icon: mdi:server
  id: IntelServer
  theme: midnight
  cards:

    - type: "custom:mini-graph-card"
      entities: 
        - entity: sensor.nzbget_disk_free 
          name: Free Space (Internal)
          show_state: true
      # entity: sensor.nzbget_disk_free
      # name: Free Space (Internal)
      icon: mdi:harddisk
      unit: MB
      height: 200
      accuracy: 50        
      hours_to_show: 24
      more_info: false
      points_per_hour: 1

    - type: "custom:mini-graph-card"
      entities: 
        - entity: sensor.nzbget_speed 
          name: Downloads
          show_state: true
      icon: mdi:cloud-download
      unit: MB/s
      height: 200
      accuracy: 50
      hours_to_show: 24
      more_info: false
      points_per_hour: 1

    - type: horizontal-stack
      # column_width: calc(100% / 3)
      cards:

      - type: "custom:mini-graph-card"
        entities: 
          - entity: sensor.unifi_gateway_speedtest_download 
            name: Download Speed
            show_state: true
          - entity: sensor.unifi_gateway_speedtest_upload
            name: Upload Speed
            show_state: true
        icon: mdi:cloud-download
        unit: Mbit/s
        height: 200
        accuracy: 50
        hours_to_show: 24
        more_info: false
        points_per_hour: 1

      # - type: "custom:mini-graph-card"
      #   entities: 
      #     - entity: sensor.speedtest_upload 
      #       name: Upload
      #       show_state: true
      #   icon: mdi:cloud-download
      #   unit: Mbit/s
      #   height: 200
      #   accuracy: 50
      #   hours_to_show: 24
      #   more_info: true
      #   points_per_hour: 1

      - type: "custom:mini-graph-card"
        entities: 
          - entity: sensor.unifi_gateway_speedtest_ping 
            name: Ping
            show_state: true
        icon: mdi:cloud-download
        unit: ms
        height: 200
        accuracy: 50
        hours_to_show: 24
        more_info: false
        points_per_hour: 1




    - type: entities
      entities:
        - entity: sensor.nzbget_article_cache
        - entity: sensor.nzbget_average_speed
        - entity: sensor.nzbget_disk_free
        - entity: sensor.nzbget_download_paused
        - entity: sensor.nzbget_post_processing_paused
        - entity: sensor.nzbget_queue_size
        - entity: sensor.nzbget_size
        - entity: sensor.nzbget_speed
        - entity: sensor.nzbget_uptime
        - entity: sensor.nzbget_post_processing_jobs
    - type: entities
      title: Home-Assistant
      show_header_toggle: false
      entities:
        - sensor.hass_uptime
        - sensor.ha_version
        - sensor.ha_github_version
        - sensor.ha_pypi_version
        - sensor.ha_version_docker_stable
    - type: entities
      title: Docker
      show_header_toggle: false
      entities:
        - switch.adguardhome
        - switch.adminer
        # - switch.airsonos
        - switch.alertmanager
        - switch.caddy
        - switch.cadvisor
        - switch.dozzle
        - switch.godaddyddns
        - switch.grafana
        - switch.ha_dockermon
        - switch.ha_monitor_api
        - switch.homeassistant
        - switch.mariadb
        - switch.mqtt
        - switch.nodeexporter
        - switch.nodered
        - switch.nzbget
        - switch.prometheus
        - switch.radarr
        - switch.sonarr
        - switch.tautulli
        - switch.unifi_controller
        - switch.unifi_mongo
        - switch.unifi_poller
        - switch.xboxrestapi
        - switch.zigbee2mqtt