#-------------------------------------------
#  Binary_sensor Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

binary_sensor.docker_adguardhome_versioncheck:
  friendly_name: "Docker Adguardhome Versioncheck"
  icon: mdi:docker

binary_sensor.docker_adminer_versioncheck:
  friendly_name: "Docker Adminer Versioncheck"
  icon: mdi:docker

binary_sensor.docker_airconnect_versioncheck:
  friendly_name: "Docker Airconnect Versioncheck"
  icon: mdi:docker

binary_sensor.docker_alertmanager_versioncheck:
  friendly_name: "Docker Alertmanager Versioncheck"
  icon: mdi:docker

binary_sensor.docker_caddy_versioncheck:
  friendly_name: "Docker Caddy Versioncheck"
  icon: mdi:docker

binary_sensor.docker_cadvisor_versioncheck:
  friendly_name: "Docker Cadvisor Versioncheck"
  icon: mdi:docker

binary_sensor.docker_dozzle_versioncheck:
  friendly_name: "Docker Dozzle Versioncheck"
  icon: mdi:docker

binary_sensor.docker_grafana_versioncheck:
  friendly_name: "Docker Grafana Versioncheck"
  icon: mdi:docker

binary_sensor.docker_homeassistant_versioncheck:
  friendly_name: "Docker Homeassistant Versioncheck"
  icon: mdi:docker

binary_sensor.docker_mariadb_versioncheck:
  friendly_name: "Docker Mariadb Versioncheck"
  icon: mdi:docker

binary_sensor.docker_mqtt_versioncheck:
  friendly_name: "Docker Mqtt Versioncheck"
  icon: mdi:docker

binary_sensor.docker_nodeexporter_versioncheck:
  friendly_name: "Docker Nodeexporter Versioncheck"
  icon: mdi:docker

binary_sensor.docker_nodered_versioncheck:
  friendly_name: "Docker Nodered Versioncheck"
  icon: mdi:docker

binary_sensor.docker_nzbget_versioncheck:
  friendly_name: "Docker Nzbget Versioncheck"
  icon: mdi:docker

binary_sensor.docker_prometheus_versioncheck:
  friendly_name: "Docker Prometheus Versioncheck"
  icon: mdi:docker

binary_sensor.docker_radarr_versioncheck:
  friendly_name: "Docker Radarr Versioncheck"
  icon: mdi:docker

binary_sensor.docker_sonarr_versioncheck:
  friendly_name: "Docker Sonarr Versioncheck"
  icon: mdi:docker

binary_sensor.docker_tautulli_versioncheck:
  friendly_name: "Docker Tautulli Versioncheck"
  icon: mdi:docker

binary_sensor.docker_unifi_controller_versioncheck:
  friendly_name: "Docker Unifi Controller Versioncheck"
  icon: mdi:docker

binary_sensor.docker_unifi_mongo_versioncheck:
  friendly_name: "Docker Unifi Mongo Versioncheck"
  icon: mdi:docker

binary_sensor.docker_unifi_poller_versioncheck:
  friendly_name: "Docker Unifi Poller Versioncheck"
  icon: mdi:docker

binary_sensor.docker_zigbee2mqtt_versioncheck:
  friendly_name: "Docker Zigbee2mqtt Versioncheck"
  icon: mdi:docker

binary_sensor.hallway_open_window:
  friendly_name: "Hallway Open Window"
  device_class: window

binary_sensor.hue_motion_sensor_occupancy:
  friendly_name: "Hue Motion Sensor Occupancy"
  device_class: motion

binary_sensor.hue_motion_sensor_update_available:
  friendly_name: "Hue Motion Sensor Update Available"

binary_sensor.kids_bedroom_open_window:
  friendly_name: "Kids Bedroom Open Window"
  device_class: window

binary_sensor.kitchen_open_window:
  friendly_name: "Kitchen Open Window"
  device_class: window

binary_sensor.landing_boiler:
  friendly_name: "Boiler"
  icon: mdi:thermometer-chevron-down
  device_class: heat

binary_sensor.landing_open_window:
  friendly_name: "Landing Open Window"
  device_class: window

binary_sensor.living_room_open_window:
  friendly_name: "Living Room Open Window"
  device_class: window

binary_sensor.master_bedroom_open_window:
  friendly_name: "Master Bedroom Open Window"
  device_class: window

binary_sensor.office_pc_connected:
  friendly_name: "Office Pc - Connected"
  device_class: connectivity

binary_sensor.office_smartthing_motion_sensor_motion:
  friendly_name: "Office Smartthing Motion Sensor Motion"
  device_class: motion

binary_sensor.office_smartthing_motion_sensor_tamper:
  friendly_name: "Office Smartthing Motion Sensor Tamper"
  device_class: problem

binary_sensor.smartthings_multi_sensor_2015_model_contact:
  friendly_name: "Smartthings Multi Sensor (2015 Model) Contact"
  device_class: door

binary_sensor.steam_wishlist_ace_of_spades_battle_builder:
  friendly_name: "Ace Of Spades: Battle Builder"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_ark_survival_evolved:
  friendly_name: "Ark: Survival Evolved"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_cities_skylines_after_dark:
  friendly_name: "Cities: Skylines - After Dark"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_cities_skylines_snowfall:
  friendly_name: "Cities: Skylines - Snowfall"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_elite_dangerous:
  friendly_name: "Elite Dangerous"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_far_cry_r_3_deluxe_bundle_dlc:
  friendly_name: "Far Cry® 3 Deluxe Bundle Dlc"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_game_dev_tycoon:
  friendly_name: "Game Dev Tycoon"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_playerunknown_s_battlegrounds:
  friendly_name: "Playerunknown's Battlegrounds"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_rapture_rejects:
  friendly_name: "Rapture Rejects"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_rocket_league_r:
  friendly_name: "Rocket League®"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_rust:
  friendly_name: "Rust"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_the_witcher_r_3_wild_hunt:
  friendly_name: "The Witcher® 3: Wild Hunt"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_this_war_of_mine:
  friendly_name: "This War Of Mine"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_tropico_4_modern_times:
  friendly_name: "Tropico 4: Modern Times"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_two_point_hospital_bigfoot:
  friendly_name: "Two Point Hospital: Bigfoot"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.steam_wishlist_two_point_hospital_pebberley_island:
  friendly_name: "Two Point Hospital: Pebberley Island"
  icon: mdi:steam
  unit_of_measurement: "on sale"

binary_sensor.surface_book_battery_status:
  friendly_name: "Surface Book - Battery Status"
  device_class: plug

binary_sensor.surface_book_charging:
  friendly_name: "Surface Book - Charging"
  device_class: plug

binary_sensor.surface_book_connected:
  friendly_name: "Surface Book - Connected"
  device_class: connectivity

binary_sensor.updater:
  friendly_name: "Updater"