#-------------------------------------------
#  Calendar Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

calendar.family_bills:
  friendly_name: "Bills"

calendar.family_birthdays:
  friendly_name: "Birthdays"