#-------------------------------------------
#  Input_boolean Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

input_boolean.ch_kiosk_mode:
  friendly_name: "Kiosk Mode"
  icon: mdi:overscan

input_boolean.lovelace_toggle:
  friendly_name: "Show Lovelace Entities"
  icon: mdi:eye-off-outline

input_boolean.node_red:
  friendly_name: "Node Red Watchdog"

input_boolean.toggle_hidden_elements:
  friendly_name: "Toggle Hidden Elements"
  icon: mdi:wrench