#-------------------------------------------
#  Light Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

light.hallway:
  friendly_name: "Hallway"

light.hallway_storage:
  friendly_name: "Hallway Storage"

light.kids_bedroom:
  friendly_name: "Kids Bedroom"

light.landing_1:
  friendly_name: "Landing 1"

light.landing_2:
  friendly_name: "Landing 2"

light.landing_group:
  friendly_name: "Landing Group"

light.lightpack2:
  friendly_name: "Lightpack2"

light.living_room_floor_lamp:
  friendly_name: "Floor Lamp"

light.living_room_lamps:
  friendly_name: "Living Room Lamps"

light.living_room_table_lamp:
  friendly_name: "Table Lamp"

light.master_bedroom:
  friendly_name: "Master Bedroom"