#-------------------------------------------
#  Media Player Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

media_player.everywhere:
  friendly_name: Alexa Group (Everywhere)

media_player.hallway_echo:
  friendly_name: Hallway Echo

media_player.kitchen_dot:
  friendly_name: Kitchen Dot

media_player.kitchen_sonos:
  friendly_name: Kitchen Sonos

media_player.living_room_kodi:
  friendly_name: Living Room Kodi

media_player.living_room_lg_netcast:
  friendly_name: Living Room Lg Netcast

media_player.living_room_plexapp:
  friendly_name: Living Room Plexapp

media_player.living_room_shield_cast:
  friendly_name: Living Room Cast

media_player.living_room_sonos:
  friendly_name: Living Room Sonos

media_player.living_room_xboxone:
  friendly_name: Living Room Xboxone

media_player.master_bedroom_dot:
  friendly_name: Master Bedroom Dot

media_player.office_dot:
  friendly_name: Office Dot

media_player.phone_bob_plexamp:
  friendly_name: Phone Bob Plexamp

media_player.phone_bob_plexapp:
  friendly_name: Phone Bob Plexapp

media_player.xbox_one:
  friendly_name: Xbox One