#-------------------------------------------
#  Switch Customisation
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Documentation:
# https://www.home-assistant.io/docs/configuration/customizing-devices/
#-------------------------------------------

switch.adguard_filtering:
  friendly_name: Adguard Filtering
  icon: mdi:shield-check

switch.adguard_parental_control:
  friendly_name: Adguard Parental Control
  icon: mdi:shield-check

switch.adguard_protection:
  friendly_name: Adguard Protection
  icon: mdi:shield-check

switch.adguard_query_log:
  friendly_name: Adguard Query Log
  icon: mdi:shield-check

switch.adguard_safe_browsing:
  friendly_name: Adguard Safe Browsing
  icon: mdi:shield-check

switch.adguard_safe_search:
  friendly_name: Adguard Safe Search
  icon: mdi:shield-check

switch.everywhere_do_not_disturb_switch:
  friendly_name: Everywhere Do Not Disturb Switch
  icon: mdi:do-not-disturb-off
  device_class: switch

switch.everywhere_repeat_switch:
  friendly_name: Everywhere Repeat Switch
  hidden: True
  icon: mdi:repeat-off
  device_class: switch

switch.everywhere_shuffle_switch:
  friendly_name: Everywhere Shuffle Switch
  hidden: True
  icon: mdi:shuffle-disabled
  device_class: switch

switch.hallway_echo_do_not_disturb_switch:
  friendly_name: Hallway Echo Do Not Disturb Switch
  icon: mdi:do-not-disturb
  device_class: switch

switch.hallway_echo_repeat_switch:
  friendly_name: Hallway Echo Repeat Switch
  hidden: True
  icon: mdi:repeat-off
  device_class: switch

switch.hallway_echo_shuffle_switch:
  friendly_name: Hallway Echo Shuffle Switch
  hidden: True
  icon: mdi:shuffle-disabled
  device_class: switch

switch.kitchen_dot_do_not_disturb_switch:
  friendly_name: Kitchen Dot Do Not Disturb Switch
  icon: mdi:do-not-disturb-off
  device_class: switch

switch.kitchen_dot_repeat_switch:
  friendly_name: Kitchen Dot Repeat Switch
  hidden: True
  icon: mdi:repeat-off
  device_class: switch

switch.kitchen_dot_shuffle_switch:
  friendly_name: Kitchen Dot Shuffle Switch
  hidden: True
  icon: mdi:shuffle-disabled
  device_class: switch

switch.master_bedroom_dot_do_not_disturb_switch:
  friendly_name: Master Bedroom Dot Do Not Disturb Switch
  icon: mdi:do-not-disturb-off
  device_class: switch

switch.master_bedroom_dot_repeat_switch:
  friendly_name: Master Bedroom Dot Repeat Switch
  hidden: True
  icon: mdi:repeat-off
  device_class: switch

switch.master_bedroom_dot_shuffle_switch:
  friendly_name: Master Bedroom Dot Shuffle Switch
  hidden: True
  icon: mdi:shuffle-disabled
  device_class: switch

switch.office_dot_do_not_disturb_switch:
  friendly_name: Office Dot Do Not Disturb Switch
  icon: mdi:do-not-disturb-off
  device_class: switch

switch.office_dot_repeat_switch:
  friendly_name: Office Dot Repeat Switch
  hidden: True
  icon: mdi:repeat-off
  device_class: switch

switch.office_dot_shuffle_switch:
  friendly_name: Office Dot Shuffle Switch
  hidden: True
  icon: mdi:shuffle-disabled
  device_class: switch

switch.remote_living_room_shield:
  friendly_name: Shield Tv
  icon: mdi:cast-off

switch.remote_living_room_skyq:
  friendly_name: Skyq
  icon: mdi:television

switch.remote_living_room_xbox:
  friendly_name: Xbox
  icon: mdi:xbox-controller-off

switch.smartpower_outlet:
  friendly_name: Smartpower Outlet

switch.smartthings_outlet_switch:
  friendly_name: Smartthings Outlet Switch

switch.zigbee2mqtt_main_join:
  friendly_name: Zigbee2mqtt Main Join
