#-------------------------------------------
#  Automations added by the front end to be converted
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------
