#-------------------------------------------
#  Dwains Theme configuration
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Theme details available on below site
# https://dwainscheeren.github.io/lovelace-dwains-theme/
#-------------------------------------------

custom_header:
  !include dwains-theme/plugins/custom_header/configuration.yaml
      
button_card_templates:
  !include_dir_merge_named dwains-theme/plugins/button-cards-templates        
 
background: var(--background-image)
views:
  !include_dir_merge_list dwains-theme/views/main/