#-------------------------------------------
#  My Admin Theme configuration
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

resources: !include_dir_merge_list ./dwains-theme/resources/

custom_header:
  !include ./lovelace/plugins/custom_header/configuration.yaml

background: var(--background-image)

views:
  !include_dir_merge_list ./lovelace/views/main/

button_card_templates:
  !include_dir_merge_named ./lovelace/plugins/button-cards-templates