#-------------------------------------------
#  TTS Configuration
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Integration Details:
# https://www.home-assistant.io/integrations/#text-to-speech
#-------------------------------------------

- platform: google_translate
  service_name: google_say