#-------------------------------------------
#  Utility Meter Configuration
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Integration Details:
# https://www.home-assistant.io/integrations/utility_meter/
#-------------------------------------------

hourly_energy:
  source: sensor.aeotec_power_monitor_energy_meter
  cycle: hourly
daily_energy:
  source: sensor.aeotec_power_monitor_energy_meter
  cycle: daily
monthly_energy:
  source: sensor.aeotec_power_monitor_energy_meter
  cycle: monthly