#-------------------------------------------
#  Withings Configuration
#  @Whatdaybob
#  Original Repo : https://github.com/whatdaybob/Home-AssistantConfig
#-------------------------------------------

#-------------------------------------------
# Integration Details:
# https://www.home-assistant.io/integrations/withings/
#-------------------------------------------

client_id: !secret withings_client_id
client_secret: !secret withings_client_secret
profiles:
  - !secret withings_profile_1
  - !secret withings_profile_2
  - !secret withings_profile_3