# Power usage addon for displaying Power, Gas and Water usage

- type: custom:dwains-flexbox-card
  padding: true
  items_classes: 'col-lg-6 col-md-6 col-sm-12 col-xs-12'
  cards:

# Power usage
  - type: vertical-stack
    cards:
# Power Graph
    - type: custom:mini-graph-card
      style: |
        ha-card {
          background-color: var(--dwains-theme-primary);
        }
      entities:
        - entity: sensor.current_power_usage
          icon: mdi:flash
      name: Power Usage
      line_color: 'var(--dwains-theme-accent)'
      hours_to_show: 24
      hour24: true
      points_per_hour: 2
      decimals: 0
      show:
        graph: bar
        extrema: true
        average: true
# Power info
    - type: entities
      entities:
        - entity: sensor.average_power_usage
          name: Average
        - entity: sensor.average_daily_power_usage
          name: Average daily
        - entity: sensor.power_cost_today
          name: Cost today
      title: Info
      show_header_toggle: false 

# Gas usage
  # - type: vertical-stack
  #   cards:
# Gas Graph
    # - type: custom:mini-graph-card
    #   style: |
    #     ha-card {
    #       background-color: var(--dwains-theme-primary);
    #     }
    #   entities:
    #     - sensor.current_gas_usage
    #   name: Gas Usage
    #   line_color: 'var(--dwains-theme-accent)'
    #   hours_to_show: 24
    #   hour24: true
    #   points_per_hour: 2
    #   decimals: 3
    #   show:
    #     graph: bar
    #     extrema: true
    #     average: true
# Gas Info
    # - type: entities
    #   entities:
    #     - entity: sensor.average_gas_usage
    #       name: Average
    #     - entity: sensor.average_daily_gas_usage
    #       name: Average daily
    #     - entity: sensor.gas_cost_today
    #       name: Cost today
    #   title: Info
    #   show_header_toggle: false 
        
# Water usage
#  - type: vertical-stack
#    cards:
# Water Graph
#    - type: custom:mini-graph-card
#      style: |
#        ha-card {
#          background-color: var(--dwains-theme-primary);
#        }
#      entities:
#        - sensor.current_water_usage
#      name: Water Usage
#      line_color: 'var(--dwains-theme-accent)'
#      hours_to_show: 24
#      hour24: true
#      points_per_hour: 2
#      #decimals: 0
#      show:
#        graph: bar
#        extrema: true
#        average: true
# Water Info
#    - type: entities
#      entities:
#        - entity: sensor.average_water_usage
#          name: Average
#        - entity: sensor.average_daily_water_usage
#          name: Average daily
#        - entity: sensor.water_cost_today
#          name: Cost today
#      title: Info
#      show_header_toggle: false 