# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

# more_page:
#   addons:
#     - name: Hello more page
#       icon: fas:chart-area
#       path: 'dwains-theme/addons/more_page/hello-more-page/page.yaml'
#       data:
#         some_data: 'This is some data parsed.'
#         some_other_data: 'and some other data.'
more_page:
    addons:
      - name: Media
        icon: fas:photo-video
        path: 'dwains-theme/addons/more_page/upcoming_media/page.yaml'
      - name: Coronavirus
        icon: fas:disease
        path: 'dwains-theme/addons/more_page/coronavirus/page.yaml'
      - name: AdGuard
        icon: fas:ad
        path: 'dwains-theme/addons/more_page/adguard/page.yaml'
      - name: Home Assistant
        icon: mdi:home-assistant
        path: 'dwains-theme/addons/more_page/ha_view/ha_monitoring.yaml'
      - name: Power Usage
        icon: fas:tachometer-alt
        path: 'dwains-theme/addons/more_page/power_usage/power_usage.yaml'
      - name: Ubiquiti UniFi
        icon: fas:network-wired
        path: 'dwains-theme/addons/more_page/ubiquiti/unifi.yaml'
