# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/rooms.html

rooms:
  - name: Hallway
    icon: fas:key
    light: light.hallway_light
    temperature: sensor.hallway_temperature
    climate: climate.hallway
    humidity: sensor.hallway_humidity
    # motion: binary_sensor.hallway_sensor_motion
    door: binary_sensor.smartthings_multi_sensor_2015_model_contact
    window: binary_sensor.hallway_open_window
    # vacuum: 
    #   entity: vacuum.rockrobo
    #   camera: camera.rockrobo_map
    # plant: plant.hallway_plant
    media_player: media_player.hallway_echo
    more_entities:
      entities:
        - entity: sensor.hallway_motion_battery_level
        - entity: sensor.smokedetector_battery



  - name: Living Room
    icon: fas:tv
    light: light.living_room_lamps
    temperature: sensor.living_room_temperature
    climate: climate.living_room
    humidity: sensor.living_room_humidity
    # motion: binary_sensor.hallway_sensor_motion
    # door: binary_sensor.hallway_door_contact
    window: binary_sensor.living_room_open_window
    # vacuum: 
    #   entity: vacuum.rockrobo
    #   camera: camera.rockrobo_map
    # plant: plant.hallway_plant
    trakt: sensor.server_trakt_upcoming
    media_player: media_player.living_room_universal
    more_entities:
      entities:
        - entity: sensor.hallway_motion_battery_level
        - entity: sensor.smokedetector_battery
    addons:
      # - name: Trakt Upcoming
      #   icon: fas:calendar
      #   path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_page.yaml'
      #   button_path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_button.yaml'
      #   data:
      #     entity: sensor.server_trakt_upcoming
      # - name: Plex New Movies
      #   icon: fas:film
      #   path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_page.yaml'
      #   button_path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_button.yaml'
      #   data:
      #     entity: sensor.server_plex_recently_added_movies
      # - name: Plex New TV
      #   icon: fas:tv
      #   path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_page.yaml'
      #   button_path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_button.yaml'
      #   data:
      #     entity: sensor.server_plex_recently_added_tv
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/living_room/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/living_room/sonos/button.yaml'
        data:
          entity: media_player.living_room_sonos
      # - name: Radarr Upcoming
      #   # icon: fas:weight
      #   path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_page.yaml'
      #   button_path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_button.yaml'
      #   data:
      #     entity: sensor.radarr_upcoming_media
      # - name: Sonarr Upcoming
      #   # icon: fas:weight
      #   path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_page.yaml'
      #   button_path: 'dwains-theme/addons/rooms/living_room/upcomingmedia_button.yaml'
      #   data:
      #     entity: sensor.sonarr_upcoming_media

  - name: Master Bedroom
    icon: fas:bed
    light: light.master_bedroom_main
    temperature: sensor.master_bedroom_temperature
    climate: climate.master_bedroom
    humidity: sensor.master_bedroom_humidity
    media_player: media_player.master_bedroom_dot
    window: binary_sensor.master_bedroom_open_window
    more_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2
    page_entities:
      columns: 1 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2

  - name: Kids Bedroom
    icon: fas:child
    light: light.kids_bedroom
    temperature: sensor.kids_bedroom_temperature
    climate: climate.kids_bedroom
    humidity: sensor.kids_bedroom_humidity
    media_player: media_player.kids_bedroom_dot
    window: binary_sensor.kids_bedroom_open_window
    more_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2
    page_entities:
      columns: 1 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2

  - name: Kitchen
    icon: fas:utensils
    # light: light.kitchen
    temperature: sensor.kitchen_temperature
    climate: climate.kitchen
    humidity: sensor.kitchen_humidity
    media_player: media_player.kitchen_sonos
    window: binary_sensor.kitchen_open_window
    more_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.kitchen_alexa_rx
        - entity: sensor.kitchen_alexa_tx
        - entity: device_tracker.kitchen_alexa
        - entity: device_tracker.kitchen_sonos
        - entity: sensor.kitchen_dot_next_alarm
        - entity: sensor.kitchen_dot_next_reminder
        - entity: sensor.kitchen_dot_next_timer
        - entity: sensor.kitchen_early_start
        - entity: sensor.kitchen_heating
        - entity: sensor.kitchen_link
        - entity: sensor.kitchen_open_window
        - entity: sensor.kitchen_overlay
        - entity: sensor.kitchen_power
        - entity: sensor.kitchen_sonos_rx
        - entity: sensor.kitchen_sonos_tx
        - entity: sensor.kitchen_tado_mode
        - entity: sensor.kitchen_temperature
        - entity: switch.kitchen_dot_do_not_disturb_switch
        - entity: switch.kitchen_dot_repeat_switch
        - entity: switch.kitchen_dot_shuffle_switch
    page_entities:
      columns: 1 #optional
      entities:
        - entity: media_player.kitchen_dot
        - entity: sensor.kitchen_mold
    addons:
      - name: Sonos
        icon: fal:speaker
        path: 'dwains-theme/addons/rooms/kitchen/sonos/page.yaml'
        button_path: 'dwains-theme/addons/rooms/kitchen/sonos/button.yaml'
        data:
          entity: media_player.kitchen_sonos

  - name: Office
    icon: fas:briefcase
    # light: light.office
    temperature: sensor.office_smartthing_motion_sensor_temperature
    # climate: climate.office
    # humidity: sensor.office_humidity
    media_player: media_player.office_dot
    # window: binary_sensor.office_open_window
    motion: binary_sensor.office_smartthing_motion_sensor_motion
    more_entities:
      columns: 2 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2
    page_entities:
      columns: 1 #optional
      entities:
        - entity: sensor.name1
        - entity: sensor.name2

  - name: Bathroom
    icon: fas:toilet-paper
    # light: light.bathroom
    # temperature: sensor.bathroom_temperature
    # climate: climate.bathroom
    # humidity: sensor.bathroom_humidity
    # media_player: media_player.bathroom_dot
    # window: binary_sensor.bathroom_open_window
    more_entities:
      columns: 2 #optional
      entities:
        - entity: device_tracker.bathroom_scales
    page_entities:
      columns: 1 #optional
      entities:
        - entity: device_tracker.bathroom_scales
    addons:
      - name: Withings Data
        icon: fas:weight
        path: 'dwains-theme/addons/rooms/bathroom/scales_page.yaml'
        button_path: 'dwains-theme/addons/rooms/bathroom/scales_button.yaml'
        data:
          entity: sensor.withings_weight_stlb_bob